// GENERATED by FishIT-Mapper KotlinPoet generator. DO NOT EDIT.
@file:Suppress(
  "RedundantVisibilityModifier",
  "unused",
)

package dev.fishit.mapper.contract

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlinx.datetime.Instant
import kotlinx.serialization.Serializable

/**
 * A point in a record-chain. Can branch by referencing a parent point.
 */
@Serializable
public data class ChainPoint(
  public val id: ChainPointId,
  public val label: String,
  public val url: String? = null,
  public val nodeId: NodeId? = null,
  public val parentId: ChainPointId? = null,
  public val notes: String? = null,
)

/**
 * A user-defined chain of points for repeatable navigation workflows.
 */
@Serializable
public data class RecordChain(
  public val id: ChainId,
  public val name: String,
  public val createdAt: Instant,
  public val points: List<ChainPoint> = emptyList(),
)

/**
 * Top-level chains container, typically stored as `chains.json`.
 */
@Serializable
public data class ChainsFile(
  public val chains: List<RecordChain> = emptyList(),
)
