// GENERATED by FishIT-Mapper KotlinPoet generator. DO NOT EDIT.
@file:Suppress(
  "RedundantVisibilityModifier",
  "unused",
)

package dev.fishit.mapper.contract

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List

/**
 * A simple index of generated types (useful for debugging and sanity checks).
 */
public object ContractIndex {
  public val types: List<String> = listOf("ContractInfo", "FishitJson", "NodeKind", "EdgeKind",
      "ResourceKind", "ConsoleLevel", "Attributes", "ProjectId", "SessionId", "EventId", "NodeId",
      "EdgeId", "ChainId", "ChainPointId", "MapNode", "MapEdge", "MapGraph", "ProjectMeta",
      "RecorderEvent", "NavigationEvent", "ResourceRequestEvent", "ConsoleMessageEvent",
      "UserActionEvent", "CustomEvent", "RecordingSession", "ChainPoint", "RecordChain",
      "ChainsFile", "ExportManifest")
}
