// GENERATED by FishIT-Mapper KotlinPoet generator. DO NOT EDIT.
@file:Suppress(
  "RedundantVisibilityModifier",
  "unused",
)

package dev.fishit.mapper.contract

import kotlin.String
import kotlin.Suppress
import kotlinx.serialization.json.Json

/**
 * Constants for the generated FishIT contract.
 */
public object ContractInfo {
  public const val APP_NAME: String = "FishIT-Mapper"

  public const val CONTRACT_VERSION: String = "0.1.0"

  public const val BUNDLE_FORMAT_VERSION: String = "0.1.0"

  public const val CLASS_DISCRIMINATOR: String = "type"
}

/**
 * Default Json configuration used across FishIT-Mapper.
 */
public val FishitJson: Json = Json {
      prettyPrint = true
      ignoreUnknownKeys = true
      encodeDefaults = true
      explicitNulls = false
      classDiscriminator = ContractInfo.CLASS_DISCRIMINATOR
    }
