// GENERATED by FishIT-Mapper KotlinPoet generator. DO NOT EDIT.
@file:Suppress(
  "RedundantVisibilityModifier",
  "unused",
)

package dev.fishit.mapper.contract

import kotlin.Suppress
import kotlinx.serialization.Serializable

/**
 * Kind of a node in the website map graph.
 */
@Serializable
public enum class NodeKind {
  Page,
  ApiEndpoint,
  Asset,
  Document,
  Form,
  Error,
  Unknown,
}

/**
 * Kind of a directed edge between nodes.
 */
@Serializable
public enum class EdgeKind {
  Link,
  Redirect,
  Fetch,
  Xhr,
  FormSubmit,
  AssetLoad,
  Embed,
  Unknown,
}

/**
 * Best-effort classification of WebView resource requests.
 */
@Serializable
public enum class ResourceKind {
  Document,
  Stylesheet,
  Script,
  Image,
  Font,
  Media,
  Fetch,
  Xhr,
  Other,
}

/**
 * Log level for console events (if captured).
 */
@Serializable
public enum class ConsoleLevel {
  Log,
  Info,
  Warn,
  Error,
}
