// GENERATED by FishIT-Mapper KotlinPoet generator. DO NOT EDIT.
@file:Suppress(
  "RedundantVisibilityModifier",
  "unused",
)

package dev.fishit.mapper.contract

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlinx.datetime.Instant
import kotlinx.serialization.Serializable

/**
 * Manifest describing an exported FishIT bundle (zip).
 */
@Serializable
public data class ExportManifest(
  public val appName: String,
  public val bundleFormatVersion: String,
  public val contractVersion: String,
  public val createdAt: Instant,
  public val project: ProjectMeta,
  public val graphPath: String = "graph.json",
  public val chainsPath: String = "chains.json",
  public val sessionsDir: String = "sessions",
  public val sessionFiles: List<String> = emptyList(),
)
