// GENERATED by FishIT-Mapper KotlinPoet generator. DO NOT EDIT.
@file:Suppress(
  "RedundantVisibilityModifier",
  "unused",
)

package dev.fishit.mapper.contract

import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlinx.datetime.Instant
import kotlinx.serialization.Serializable

/**
 * A node in the website map graph.
 */
@Serializable
public data class MapNode(
  public val id: NodeId,
  public val kind: NodeKind,
  public val url: String,
  public val title: String? = null,
  public val tags: List<String> = emptyList(),
  public val attributes: Attributes = emptyMap(),
  public val firstSeenAt: Instant? = null,
  public val lastSeenAt: Instant? = null,
)

/**
 * A directed edge between two nodes.
 */
@Serializable
public data class MapEdge(
  public val id: EdgeId,
  public val kind: EdgeKind,
  public val from: NodeId,
  public val to: NodeId,
  public val label: String? = null,
  public val attributes: Attributes = emptyMap(),
  public val firstSeenAt: Instant? = null,
  public val lastSeenAt: Instant? = null,
)

/**
 * A snapshot of the full mapping graph.
 */
@Serializable
public data class MapGraph(
  public val nodes: List<MapNode> = emptyList(),
  public val edges: List<MapEdge> = emptyList(),
  public val updatedAt: Instant? = null,
)
