// GENERATED by FishIT-Mapper KotlinPoet generator. DO NOT EDIT.
@file:Suppress(
  "RedundantVisibilityModifier",
  "unused",
)

package dev.fishit.mapper.contract

import kotlin.String
import kotlin.Suppress
import kotlin.collections.Map
import kotlin.jvm.JvmInline
import kotlinx.serialization.Serializable

/**
 * Arbitrary key/value attributes. Keep values small and serializable.
 */
public typealias Attributes = Map<String, String>

/**
 * Stable identifier for a mapping project.
 */
@JvmInline
@Serializable
public value class ProjectId(
  public val `value`: String,
)

/**
 * Stable identifier for a recording session.
 */
@JvmInline
@Serializable
public value class SessionId(
  public val `value`: String,
)

/**
 * Stable identifier for a recorder event.
 */
@JvmInline
@Serializable
public value class EventId(
  public val `value`: String,
)

/**
 * Stable identifier for a graph node.
 */
@JvmInline
@Serializable
public value class NodeId(
  public val `value`: String,
)

/**
 * Stable identifier for a graph edge.
 */
@JvmInline
@Serializable
public value class EdgeId(
  public val `value`: String,
)

/**
 * Stable identifier for a record chain.
 */
@JvmInline
@Serializable
public value class ChainId(
  public val `value`: String,
)

/**
 * Stable identifier for a record chain point.
 */
@JvmInline
@Serializable
public value class ChainPointId(
  public val `value`: String,
)
