// GENERATED by FishIT-Mapper KotlinPoet generator. DO NOT EDIT.
@file:Suppress(
  "RedundantVisibilityModifier",
  "unused",
)

package dev.fishit.mapper.contract

import kotlin.Boolean
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.Map
import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Metadata describing a mapping project (workspace).
 */
@Serializable
public data class ProjectMeta(
  public val id: ProjectId,
  public val name: String,
  public val startUrl: String,
  public val createdAt: Instant,
  public val updatedAt: Instant,
)

/**
 * A recorded event during a browser mapping session.
 */
@Serializable
public sealed interface RecorderEvent {
  public val id: EventId

  public val at: Instant
}

/**
 * Navigation to a new document URL.
 */
@Serializable
@SerialName("nav")
public data class NavigationEvent(
  override val id: EventId,
  override val at: Instant,
  public val url: String,
  public val fromUrl: String? = null,
  public val title: String? = null,
  public val isRedirect: Boolean = false,
) : RecorderEvent

/**
 * A resource request observed by the WebView (best effort).
 */
@Serializable
@SerialName("req")
public data class ResourceRequestEvent(
  override val id: EventId,
  override val at: Instant,
  public val url: String,
  public val initiatorUrl: String? = null,
  public val method: String? = null,
  public val resourceKind: ResourceKind? = null,
) : RecorderEvent

/**
 * A console message captured from the page (if enabled).
 */
@Serializable
@SerialName("console")
public data class ConsoleMessageEvent(
  override val id: EventId,
  override val at: Instant,
  public val level: ConsoleLevel,
  public val message: String,
) : RecorderEvent

/**
 * A user action captured by the app (tap/click/scroll etc., if enabled).
 */
@Serializable
@SerialName("action")
public data class UserActionEvent(
  override val id: EventId,
  override val at: Instant,
  public val action: String,
  public val target: String? = null,
) : RecorderEvent

/**
 * A custom event that allows extensions without breaking the schema.
 */
@Serializable
@SerialName("custom")
public data class CustomEvent(
  override val id: EventId,
  override val at: Instant,
  public val name: String,
  public val payload: Map<String, String> = emptyMap(),
) : RecorderEvent

/**
 * A recording session containing an ordered list of events.
 */
@Serializable
public data class RecordingSession(
  public val id: SessionId,
  public val projectId: ProjectId,
  public val startedAt: Instant,
  public val endedAt: Instant? = null,
  public val initialUrl: String,
  public val finalUrl: String? = null,
  public val events: List<RecorderEvent> = emptyList(),
  public val notes: String? = null,
)
